/**
 * SongStory — Static-First Data Layer
 */

let SONGS_DATA = [
    {
        "id": "back-to-back",
        "title": "Back to Back",
        "artist_id": "drake",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/drake/back-to-back.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Back to Back Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "family-matters",
        "title": "Family Matters",
        "artist_id": "drake",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/drake/family-matters.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Family Matters Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "push-ups",
        "title": "Push Ups",
        "artist_id": "drake",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/drake/push-ups.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Push Ups Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "taylor-made-freestyle",
        "title": "Taylor Made Freestyle",
        "artist_id": "drake",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/drake/taylor-made-freestyle.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Taylor Made Freestyle Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "stan",
        "title": "Stan",
        "artist_id": "eminem",
        "genre": "Rap",
        "year": 2000,
        "url": "songs/eminem/stan.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Stan Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "7-minute-drill",
        "title": "7 Minute Drill",
        "artist_id": "j-cole",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/j-cole/7-minute-drill.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/7 Minutes Drill Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "might-delete-later",
        "title": "Might Delete Later (Excuses)",
        "artist_id": "j-cole",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/j-cole/might-delete-later.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Might Delete Later (Excuses) Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "power",
        "title": "Power",
        "artist_id": "kanye-west",
        "genre": "Rap",
        "year": 2010,
        "url": "songs/kanye-west/power.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Power Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "6-16-in-LA",
        "title": "6:16 in LA",
        "artist_id": "kendrick-lamar",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/kendrick-lamar/6-16-in-LA.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/6:16 in LA Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "euphoria",
        "title": "Euphoria",
        "artist_id": "kendrick-lamar",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/kendrick-lamar/euphoria.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Euphoria Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "meet-the-grahams",
        "title": "Meet the Grahams",
        "artist_id": "kendrick-lamar",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/kendrick-lamar/meet-the-grahams.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Meet the Grahams Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "not-like-us",
        "title": "Not Like Us",
        "artist_id": "kendrick-lamar",
        "genre": "Rap",
        "year": 2024,
        "url": "songs/kendrick-lamar/not-like-us.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Not Like Us Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "lettre-a-la-republique",
        "title": "Lettre à la République",
        "artist_id": "kery-james",
        "genre": "Rap Conscient",
        "year": 2012,
        "url": "songs/kery-james/lettre-a-la-republique.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Lettre à la République Cover.webp",
        "tags": [],
        "description": ""
    },
    {
        "id": "dont-laik",
        "title": "Don't Laïk",
        "artist_id": "medine",
        "genre": "Rap Conscient",
        "year": 2012,
        "url": "songs/medine/dont-laik.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Don",
        "tags": [],
        "description": ""
    },
    {
        "id": "menace-de-mort",
        "title": "Menace de Mort",
        "artist_id": "youssoupha",
        "genre": "Rap Conscient",
        "year": 2009,
        "url": "songs/youssoupha/menace-de-mort.html",
        "audio_url": "",
        "spotify_id": "",
        "apple_music_id": "",
        "cover_url": "Images/Title Cover/Menace De Mort Cover.webp",
        "tags": [],
        "description": ""
    }
];

let ARTISTS_DATA = [];

let GLOSSARY = {};

window.loadAppDataFromSupabase = async () => console.log('Static mode enabled - No Supabase sync needed.');
